# -*- coding: utf-8 -*-
"""YoloClip_July25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19USJKvH-Jpxr7906Ra27TTbU4T3shZhb
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

# Load YOLOv10n model from scratch
model = YOLO("yolov10n.yaml")

# Train the model
model.train(data="coco8.yaml", epochs=100, imgsz=640)

from ultralytics import YOLO

# Load YOLOv10n model from scratch
model = YOLO("yolov10n.pt")

# Train the model
#model.train(data="coco8.yaml", epochs=100, imgsz=640)
results = model.train(data="SKU-110K.yaml", epochs=5, imgsz=640, batch=8)

"""Now, let's use the trained model to make a prediction on an image."""

from ultralytics import YOLO
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Load the best trained YOLOv10 model
# Corrected path to the model from the last training run (train-3)
model = YOLO('/content/runs/detect/train-3/weights/best.pt')

# Path to the image for prediction
image_path = '/content/sample_data/cooldrinks.jpg'

# Run inference on the image with slightly more lenient parameters
results = model.predict(source=image_path, conf=0.1, iou=0.3, save=True, show=False)

# Display the original image with predictions
# The predict method saves the annotated image to 'runs/detect/predict/'
# We need to find the path to the saved image to display it.
# Assuming it's saved in the default predict directory after the first prediction

# Get the path to the predicted image
import os
# The save_dir might vary (predict-N), so we'll construct it dynamically from results
predicted_image_path = os.path.join(results[0].save_dir, os.path.basename(image_path))

# Display the predicted image
img = mpimg.imread(predicted_image_path)
plt.figure(figsize=(10, 10))
plt.imshow(img)
plt.axis('off')
plt.title('Predicted Image')
plt.show()

"""To get the name of each identified object, we can iterate through the `boxes` in the `results` and use the `model.names` dictionary to retrieve the class labels."""

# Get the detected objects and their names
detected_objects = []
if results and results[0].boxes:
    for box in results[0].boxes:
        class_id = int(box.cls[0])
        object_name = model.names[class_id]
        detected_objects.append(object_name)

print("Identified Objects:")
for obj_name in detected_objects:
    print(f"- {obj_name}")

"""As explained, the YOLOv10 model trained on SKU-110K assigns a generic 'object' label. To get more specific names for each detected object, we can leverage a Zero-Shot Image Classification model like CLIP (Contrastive Language-Image Pre-training). CLIP can classify images into categories described by text, without needing to be fine-tuned on those specific categories.

First, let's install the `transformers` library, which provides an easy interface to use pre-trained CLIP models.
"""

!pip install -q transformers

"""Now, we will load the pre-trained CLIP model and its processor. Then, for each bounding box detected by YOLOv10, we will crop that region from the original image and feed it to CLIP along with a list of candidate labels. CLIP will then tell us which label from our list best describes the cropped image."""

from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch
import numpy as np

# Load pre-trained CLIP model and processor
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Move model to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
clip_model.to(device)

# Reload the original image to crop from it
original_image_path = '/content/sample_data/cooldrinks.jpg'
original_image = Image.open(original_image_path).convert("RGB")

# Define candidate labels for CLIP to classify against.
# You can modify this list to include more specific categories relevant to your use case.
# For example, if you know the types of products (e.g., 'shampoo', 'cereal box', 'drink can').
candidate_labels = [
    "beverage", "soda can", "juice box", "water bottle", "plastic bottle of drink",
    "glass bottle of drink", "Coca Cola can", "Sprite can", "Fanta can", "Pepsi can",
    "Green Sands bottle", "energy drink can", "alcoholic beverage", "wine bottle",
    "beer bottle", "milk carton", "coffee drink", "tea drink", "soft drink",
    "fruit juice", "carbonated drink", "sports drink", "drink package", "drink container"
]

print("Classifying detected objects with CLIP...")

clip_predictions = []
if results and results[0].boxes:
    for i, box in enumerate(results[0].boxes):
        # Get bounding box coordinates in xyxy format
        x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())

        # Crop the object from the original image
        cropped_image = original_image.crop((x1, y1, x2, y2))

        # Prepare inputs for CLIP
        inputs = clip_processor(text=candidate_labels, images=cropped_image, return_tensors="pt", padding=True)
        inputs = {k: v.to(device) for k, v in inputs.items()}

        # Get CLIP model outputs
        with torch.no_grad():
            outputs = clip_model(**inputs)

        # Compute similarity scores
        logits_per_image = outputs.logits_per_image # this is the image-text similarity score
        probs = logits_per_image.softmax(dim=1).cpu().numpy()[0]

        # Get the label with the highest probability
        best_label_idx = np.argmax(probs)
        best_label = candidate_labels[best_label_idx]
        confidence = probs[best_label_idx]

        clip_predictions.append({
            "box_id": i,
            "label": best_label,
            "confidence": confidence,
            "bbox": (x1, y1, x2, y2)
        })

print("\nCLIP Identified Objects with Confidence:")
for pred in clip_predictions:
    print(f"- Object {pred['box_id']}: {pred['label']} (Confidence: {pred['confidence']:.2f})")

# Optionally, you can also visualize the cropped images and their CLIP labels
# Here's an example for the first few detections:
num_to_display = min(50, len(clip_predictions))
if num_to_display > 0:
    print(f"\nDisplaying first {num_to_display} classified objects:")
    fig, axes = plt.subplots(1, num_to_display, figsize=(3 * num_to_display, 3))
    if num_to_display == 1: # Handle single subplot case
        axes = [axes]
    for i in range(num_to_display):
        pred = clip_predictions[i]
        x1, y1, x2, y2 = pred['bbox']
        cropped_image = original_image.crop((x1, y1, x2, y2))
        axes[i].imshow(cropped_image)
        axes[i].set_title(f"{pred['label']} ({pred['confidence']:.2f})")
        axes[i].axis('off')
    plt.tight_layout()
    plt.show()

"""Let's count the identified objects based on their CLIP classifications."""

from collections import Counter

# Extract labels from the CLIP predictions
classified_labels = [pred['label'] for pred in clip_predictions]

# Count the occurrences of each label
label_counts = Counter(classified_labels)

print("\nObject Counts by CLIP Classification:")
for label, count in label_counts.most_common():
    print(f"- {label}: {count}")